name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python: ['3.12', '3.11', '3.10', '3.9', '3.8']
        pandoc: ['3.4', '3.3', '3.2.1', '3.1.13', '3.0.1', '2.19.2']

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Pandoc
        run: |
          # See latest versions here: https://github.com/jgm/pandoc/releases/
          wget --progress=dot:mega -O pandoc.deb "https://github.com/jgm/pandoc/releases/download/${{ matrix.pandoc }}/pandoc-${{ matrix.pandoc }}-1-amd64.deb"
          sudo dpkg --install pandoc.deb
          rm pandoc.deb

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python }}'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python3 -m pip install -r requirements-dev.txt
          pip install .

      - name: Run tests
        run: pytest

      - name: Output success message
        run: echo "✅ All tests passed with Python ${{ matrix.python }} and pandoc ${{ matrix.pandoc }}." >> $GITHUB_STEP_SUMMARY
        if: success()

      - name: Output failure message
        run: echo "❌ Tests failed with Python ${{ matrix.python }} and pandoc ${{ matrix.pandoc }}." >> $GITHUB_STEP_SUMMARY
        if: failure()
